### ISSUE TITLE
ReCaptcha::key() must be of the type string, null returned

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#7] opened 2021-07-25 10:57 UTC
I am not using ReCaptcha but I am getting this error:

`Return value of Aerni\\LivewireForms\\Captcha\\ReCaptcha::key() must be of the type string, null returned at /xxx/vendor/aerni/livewire-forms/src/Captcha/ReCaptcha.php:58`

It might be because I just updated from 1.0 to 1.2.0-beta.4 and some old code was left behind.

Anyway, I have to update the config file to this (empty strings): 

```
'captcha' => [
  'enabled' => false,
  'key' => env('CAPTCHA_KEY', ''),
  'secret' => env('CAPTCHA_SECRET', '')
],
```

**Comment by aerni** [comment] 2021-07-25 16:06
I can't reproduce this issue. I only see this exception pop up if the captcha is enabled but no key was set. If the captcha is disabled, the exception disappears.

**Comment by aerni** [comment] 2021-07-25 16:58
My guess is that this is a caching issue because you loaded the view without updating the config first.

Reset the config to the factory config and clear your view cache.

**Comment by stuartcusackie** [comment] 2021-07-27 18:40
Yep. I suspected as much but the error won't go away for whatever caching reason. I've tried the following:
`php artisan config:clear`
`php artisan cache:clear`
`php please stache:clear`

I've even ssh'd to the server to delete the package and do a `composer install` but no joy. It works locally which is odd.

I'll figure it out eventually.

**Comment by aerni** [comment] 2021-07-28 08:06
You have to clear your view: `php artisan view:clear`.

**Comment by stuartcusackie** [comment] 2021-07-28 10:10
I tried that and I'm afraid not. Still a server error but not a local error. It will probably go away when I build a new server.

**Comment by stuartcusackie** [comment] 2021-07-28 10:15
Hmm the error states:
`Return value of Aerni\\LivewireForms\\Captcha\\ReCaptcha::key() must be of the type string, null returned`

Is this function definition a problem? It must return a string but based on your config file it would return null.

```
 /**
   * Get the captcha's site key.
   */
public function key(): string
{
  return config('livewire-forms.captcha.key');
}
```

**Comment by aerni** [comment] 2021-07-28 13:13
This method only gets called by the `{{ captcha:key }}` tag or `@captchaKey` blade directive. The tag and directive are only called in the `captcha.antlers.html` and `captcha.blade.php` view. And this view only gets rendered when captcha is enabled in the config or on the form blueprint. If the view doesn't get rendered, the `key()` method is never called and should therefore not throw an exception.

I could return `?string` but really don't want to. Because a key is always needed and should never be null.

**Comment by stuartcusackie** [comment] 2021-07-28 13:37
Ah, understood.

Well I'll just keep an eye out for caching problems and see if it goes away when I launch the production server.

**Comment by aerni** [comment] 2021-07-28 13:38
Ok. Closing this for now. Let me know if you run into this issue again.

**Closed by aerni** 2021-07-28 13:38 UTC
