### ISSUE TITLE
Should fields use wire:model.defer instead of wire:model.lazy

### ISSUE THREAD

**Issue by stuartcusackie** [aerni/statamic-livewire-forms#5] opened 2021-07-23 19:53 UTC
Hi,

I'm noticing that checkboxes and text fields are dissappearring and reappearing randomly when interacting. Would wire:model.defer be a better choice when defining the models on fields?

Thanks!

**Comment by aerni** [comment] 2021-07-24 10:04
I can't reproduce this issue. You're free to publish the views and change `lazy` to `defer`.

**Comment by stuartcusackie** [comment] 2021-07-24 19:17
It might just be because I am on a windows vagrant box and there could be a delay to get a response from livewire.

I have updated lazy to defer but I also need to reset the field validation oninput or onchange. Do you know if there is a function available for this?

**Comment by stuartcusackie** [comment] 2021-07-25 11:04
I've just tested on a live server and it's 99% fine. If you click checkboxes really quickly for a while then there will be a couple of anomalies but no big deal. It might be a problem if the server is under pressure.

**Comment by aerni** [comment] 2021-07-25 16:08
I'm closing this for now as I don't think that it's an issue with this addon. You're can always publish the views and play around with it.

**Closed by aerni** 2021-07-25 16:08 UTC
